# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

env:
  FASTLANE_OPT_OUT_USAGE: 1
  RUBYOPT: "-W0"

includes:
  npm:
    taskfile: ./taskfiles/npm.yml
  tauri:
    taskfile: ./taskfiles/tauri.yml
  ios:
    taskfile: ./taskfiles/ios.yml
  android:
    taskfile: ./taskfiles/android.yml

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  bundle:install:
    desc: "Install Ruby gems from Gemfile.lock"
    cmds:
      - bundle install --quiet
    sources:
      - Gemfile
      - Gemfile.lock
    generates:
      - .bundle/config

  pre-commit:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run --all-files

  dev:
    desc: "Run Tauri in development mode"
    cmds:
      - task: tauri:dev

  build:
    desc: "Build Tauri app for current architecture"
    cmds:
      - task: tauri:build

  build:arm64:
    desc: "Build Tauri app for Apple Silicon (arm64)"
    cmds:
      - task: tauri:build:arm64

  build:x64:
    desc: "Build Tauri app for Intel (x86_64)"
    cmds:
      - task: tauri:build:x64

  clean:
    desc: "Clean all build artifacts"
    cmds:
      - task: tauri:clean
      - task: ios:clean
      - task: android:clean
      - task: npm:clean

  certs:
    desc: "Sync code signing certificates"
    cmds:
      - task: ios:certificates

  ios:
    desc: "Run on iOS simulator"
    cmds:
      - task: ios:dev

  test:
    desc: "Run Rust tests"
    cmds:
      - task: tauri:test
