# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

env:
  FASTLANE_OPT_OUT_USAGE: 1
  RUBYOPT: "-W0"

includes:
  deno:
    taskfile: ./taskfiles/deno.yml
  tauri:
    taskfile: ./taskfiles/tauri.yml
  ios:
    taskfile: ./taskfiles/ios.yml
  android:
    taskfile: ./taskfiles/android.yml

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  bundle:install:
    desc: "Install Ruby gems from Gemfile.lock"
    cmds:
      - bundle install --quiet
    sources:
      - Gemfile
      - Gemfile.lock
    generates:
      - .bundle/config

  pre-commit:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run --all-files

  dev:
    desc: "Run Tauri in development mode"
    cmds:
      - task: tauri:dev

  build:
    desc: "Build Tauri app for current architecture"
    cmds:
      - task: tauri:build

  build:arm64:
    desc: "Build Tauri app for Apple Silicon (arm64)"
    cmds:
      - task: tauri:build:arm64

  build:x64:
    desc: "Build Tauri app for Intel (x86_64)"
    cmds:
      - task: tauri:build:x64

  clean:
    desc: "Clean all build artifacts"
    cmds:
      - task: tauri:clean
      - task: ios:clean
      - task: android:clean
      - task: deno:clean

  certs:
    desc: "Sync code signing certificates"
    cmds:
      - task: ios:certificates

  ios:
    desc: "Run on iOS simulator"
    cmds:
      - task: ios:dev

  test:
    desc: "Run all tests (Rust + frontend unit)"
    cmds:
      - task: tauri:test
      - task: test:unit

  test:rust:
    desc: "Run Rust tests only"
    cmds:
      - task: tauri:test

  test:unit:
    desc: "Run frontend unit tests (Vitest)"
    dir: src-tauri/dist
    cmds:
      - npm test

  test:unit:watch:
    desc: "Run frontend unit tests in watch mode"
    dir: src-tauri/dist
    cmds:
      - npm run test:watch

  test:unit:coverage:
    desc: "Run frontend unit tests with coverage"
    dir: src-tauri/dist
    cmds:
      - npm run test:coverage

  test:e2e:
    desc: "Run Playwright E2E tests"
    dir: src-tauri/dist
    cmds:
      - npm run test:e2e

  test:e2e:ui:
    desc: "Run Playwright E2E tests with UI"
    dir: src-tauri/dist
    cmds:
      - npm run test:e2e:ui

  db:seed:
    desc: "Seed development database with sample restaurants"
    cmds:
      - sqlite3 ~/Library/Application\ Support/Lunch/lunch.db < scripts/dev_seed.sql
      - echo "Database seeded successfully"

  db:reset:
    desc: "Reset development database (delete and recreate)"
    cmds:
      - rm -f ~/Library/Application\ Support/Lunch/lunch.db
      - echo "Database deleted. Run 'task dev' to recreate, then 'task db:seed' to seed."
